# Generated by Django 4.2.2 on 2023-07-06 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_admin_contratacion', models.CharField(max_length=20)),
                ('apellido_admin_contratacion', models.CharField(max_length=20)),
                ('celular_admin_contratacion', models.CharField(max_length=20)),
                ('correo_admin_contratacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_casos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_caso', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perfil', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prestador', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional_regional', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_accion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('apellido_usuario', models.CharField(max_length=20)),
                ('cedula_usuario', models.CharField(max_length=20)),
                ('celular_usuario', models.CharField(max_length=20)),
                ('correo_usuario', models.EmailField(max_length=254)),
                ('password', models.CharField(default=0, max_length=200)),
                ('estado_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.estado')),
                ('rol_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.rol')),
            ],
        ),
        migrations.CreateModel(
            name='InformeRegistroCasos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_caso', models.CharField(max_length=20)),
                ('hora_registro_caso', models.DateTimeField()),
                ('hora_finalizacion_caso', models.DateTimeField()),
                ('analista_asignado_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.usuario')),
                ('estado_gestion_cfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.estado_casos')),
            ],
        ),
        migrations.CreateModel(
            name='InformeModificacionUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesional', models.CharField(max_length=20)),
                ('documento_profesional', models.CharField(max_length=20)),
                ('numero_caso_profesional', models.CharField(max_length=20)),
                ('fecha_informe', models.DateField()),
                ('accion_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.tipoaccion')),
                ('admin_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.admincontratacion')),
                ('especialidad_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.especialidad')),
                ('perfil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.perfil')),
                ('prestador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.prestador')),
                ('regional_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.regional')),
            ],
        ),
    ]
